stages:
  - init
  - rpmbuild
  - prepare-rhel-internal
  - test
  - cleanup
  - finish

.base:
  after_script:
    - schutzbot/update_github_status.sh update
    - schutzbot/save_journal.sh
    - schutzbot/run_cloud_cleaner.sh
  tags:
    - terraform
  artifacts:
    paths:
      - journal-log.gpg
      - ci-artifacts
    when: always

.terraform:
  extends: .base
  tags:
    - terraform

.terraform/openstack:
  extends: .base
  tags:
    - terraform/openstack


init:
  stage: init
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh start

RPM:
  stage: rpmbuild
  extends: .terraform
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
  script:
    - sh "schutzbot/mockbuild.sh"
  after_script:
    - schutzbot/update_github_status.sh update
    - schutzbot/save_journal.sh
  artifacts:
    paths:
      - journal-log.gpg
  parallel:
    matrix:
      - RUNNER:
          - aws/rhel-8.4-ga-x86_64

Packer:
  stage: test
  extends: .terraform
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
  script:
    - schutzbot/packer.sh
  variables:
    RUNNER: aws/centos-stream-8-x86_64

finish:
  stage: finish
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh finish
